# Generated by Django 4.2.6 on 2023-11-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_comment_created_alter_commentlikes_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='=attachments/posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postAttachments', to='DashboardApp.posts')),
            ],
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/comments/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAttachments', to='DashboardApp.posts')),
            ],
        ),
    ]
