# Generated by Django 4.2.6 on 2023-11-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0009_alter_postattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentAttachment',
        ),
        migrations.DeleteModel(
            name='PostAttachment',
        ),
    ]
