# Generated by Django 4.2.6 on 2023-11-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0014_file_comment_file_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.comment'),
        ),
    ]
