# Generated by Django 4.2.6 on 2023-11-07 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0015_alter_file_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DashboardApp.comment'),
        ),
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DashboardApp.posts'),
        ),
    ]
