# Generated by Django 4.2.6 on 2023-11-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0016_alter_file_comment_alter_file_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='DashboardApp.tag'),
        ),
    ]
