# Generated by Django 4.2.6 on 2024-02-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0018_alter_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='DashboardApp.tag'),
        ),
    ]
